// AUTO-GENERATED by scripts/gen-responsive.mjs - do not edit by hand.
import dev1_orig from "../assets/devotional/dev1.jpg";
import dev1_240w from "../assets/optimized/r/dev1-240.webp";
import dev1_240w_avif from "../assets/optimized/r/dev1-240.avif";
import dev1_480w from "../assets/optimized/r/dev1-480.webp";
import dev1_480w_avif from "../assets/optimized/r/dev1-480.avif";
import dev1_960w from "../assets/optimized/r/dev1-960.webp";
import dev1_960w_avif from "../assets/optimized/r/dev1-960.avif";
import dev1_fb from "../assets/optimized/r/dev1-960.webp";
import dev3_orig from "../assets/devotional/dev3.jpg";
import dev3_240w from "../assets/optimized/r/dev3-240.webp";
import dev3_240w_avif from "../assets/optimized/r/dev3-240.avif";
import dev3_480w from "../assets/optimized/r/dev3-480.webp";
import dev3_480w_avif from "../assets/optimized/r/dev3-480.avif";
import dev3_960w from "../assets/optimized/r/dev3-960.webp";
import dev3_960w_avif from "../assets/optimized/r/dev3-960.avif";
import dev3_fb from "../assets/optimized/r/dev3-960.webp";
import bride1_orig from "../assets/recepmarriage/bride1.jpg";
import bride1_240w from "../assets/optimized/r/bride1-240.webp";
import bride1_240w_avif from "../assets/optimized/r/bride1-240.avif";
import bride1_480w from "../assets/optimized/r/bride1-480.webp";
import bride1_480w_avif from "../assets/optimized/r/bride1-480.avif";
import bride1_960w from "../assets/optimized/r/bride1-960.webp";
import bride1_960w_avif from "../assets/optimized/r/bride1-960.avif";
import bride1_fb from "../assets/optimized/r/bride1-960.webp";
import bride7_orig from "../assets/recepmarriage/bride7.jpg";
import bride7_240w from "../assets/optimized/r/bride7-240.webp";
import bride7_240w_avif from "../assets/optimized/r/bride7-240.avif";
import bride7_480w from "../assets/optimized/r/bride7-480.webp";
import bride7_480w_avif from "../assets/optimized/r/bride7-480.avif";
import bride7_960w from "../assets/optimized/r/bride7-960.webp";
import bride7_960w_avif from "../assets/optimized/r/bride7-960.avif";
import bride7_fb from "../assets/optimized/r/bride7-960.webp";
import r1_orig from "../assets/recepmarriage/r1.jpg";
import r1_240w from "../assets/optimized/r/r1-240.webp";
import r1_240w_avif from "../assets/optimized/r/r1-240.avif";
import r1_480w from "../assets/optimized/r/r1-480.webp";
import r1_480w_avif from "../assets/optimized/r/r1-480.avif";
import r1_960w from "../assets/optimized/r/r1-960.webp";
import r1_960w_avif from "../assets/optimized/r/r1-960.avif";
import r1_fb from "../assets/optimized/r/r1-960.webp";
import r9_orig from "../assets/recepmarriage/r9.jpg";
import r9_240w from "../assets/optimized/r/r9-240.webp";
import r9_240w_avif from "../assets/optimized/r/r9-240.avif";
import r9_480w from "../assets/optimized/r/r9-480.webp";
import r9_480w_avif from "../assets/optimized/r/r9-480.avif";
import r9_960w from "../assets/optimized/r/r9-960.webp";
import r9_960w_avif from "../assets/optimized/r/r9-960.avif";
import r9_fb from "../assets/optimized/r/r9-960.webp";
import r10_orig from "../assets/recepmarriage/r10.jpg";
import r10_240w from "../assets/optimized/r/r10-240.webp";
import r10_240w_avif from "../assets/optimized/r/r10-240.avif";
import r10_480w from "../assets/optimized/r/r10-480.webp";
import r10_480w_avif from "../assets/optimized/r/r10-480.avif";
import r10_960w from "../assets/optimized/r/r10-960.webp";
import r10_960w_avif from "../assets/optimized/r/r10-960.avif";
import r10_fb from "../assets/optimized/r/r10-960.webp";
import r12_orig from "../assets/recepmarriage/r12.jpg";
import r12_240w from "../assets/optimized/r/r12-240.webp";
import r12_240w_avif from "../assets/optimized/r/r12-240.avif";
import r12_480w from "../assets/optimized/r/r12-480.webp";
import r12_480w_avif from "../assets/optimized/r/r12-480.avif";
import r12_960w from "../assets/optimized/r/r12-960.webp";
import r12_960w_avif from "../assets/optimized/r/r12-960.avif";
import r12_fb from "../assets/optimized/r/r12-960.webp";
import anni10_orig from "../assets/anniversory/anni10.jpg";
import anni10_240w from "../assets/optimized/r/anni10-240.webp";
import anni10_240w_avif from "../assets/optimized/r/anni10-240.avif";
import anni10_480w from "../assets/optimized/r/anni10-480.webp";
import anni10_480w_avif from "../assets/optimized/r/anni10-480.avif";
import anni10_960w from "../assets/optimized/r/anni10-960.webp";
import anni10_960w_avif from "../assets/optimized/r/anni10-960.avif";
import anni10_fb from "../assets/optimized/r/anni10-960.webp";
import baby_orig from "../assets/baby.jpg";
import baby_240w from "../assets/optimized/r/baby-240.webp";
import baby_240w_avif from "../assets/optimized/r/baby-240.avif";
import baby_480w from "../assets/optimized/r/baby-480.webp";
import baby_480w_avif from "../assets/optimized/r/baby-480.avif";
import baby_960w from "../assets/optimized/r/baby-960.webp";
import baby_960w_avif from "../assets/optimized/r/baby-960.avif";
import baby_fb from "../assets/optimized/r/baby-960.webp";
import birthday1_orig from "../assets/birthday/birthday1.png";
import birthday1_240w from "../assets/optimized/r/birthday1-240.webp";
import birthday1_240w_avif from "../assets/optimized/r/birthday1-240.avif";
import birthday1_480w from "../assets/optimized/r/birthday1-480.webp";
import birthday1_480w_avif from "../assets/optimized/r/birthday1-480.avif";
import birthday1_960w from "../assets/optimized/r/birthday1-960.webp";
import birthday1_960w_avif from "../assets/optimized/r/birthday1-960.avif";
import birthday1_fb from "../assets/optimized/r/birthday1-960.webp";
import birthday10_orig from "../assets/birthday/birthday10.png";
import birthday10_240w from "../assets/optimized/r/birthday10-240.webp";
import birthday10_240w_avif from "../assets/optimized/r/birthday10-240.avif";
import birthday10_480w from "../assets/optimized/r/birthday10-480.webp";
import birthday10_480w_avif from "../assets/optimized/r/birthday10-480.avif";
import birthday10_960w from "../assets/optimized/r/birthday10-960.webp";
import birthday10_960w_avif from "../assets/optimized/r/birthday10-960.avif";
import birthday10_fb from "../assets/optimized/r/birthday10-960.webp";
import s10_orig from "../assets/s10.png";
import s10_240w from "../assets/optimized/r/s10-240.webp";
import s10_240w_avif from "../assets/optimized/r/s10-240.avif";
import s10_480w from "../assets/optimized/r/s10-480.webp";
import s10_480w_avif from "../assets/optimized/r/s10-480.avif";
import s10_960w from "../assets/optimized/r/s10-960.webp";
import s10_960w_avif from "../assets/optimized/r/s10-960.avif";
import s10_fb from "../assets/optimized/r/s10-960.webp";
import s12_orig from "../assets/s12.png";
import s12_240w from "../assets/optimized/r/s12-240.webp";
import s12_240w_avif from "../assets/optimized/r/s12-240.avif";
import s12_480w from "../assets/optimized/r/s12-480.webp";
import s12_480w_avif from "../assets/optimized/r/s12-480.avif";
import s12_960w from "../assets/optimized/r/s12-960.webp";
import s12_960w_avif from "../assets/optimized/r/s12-960.avif";
import s12_fb from "../assets/optimized/r/s12-960.webp";
import s13_orig from "../assets/s13.png";
import s13_240w from "../assets/optimized/r/s13-240.webp";
import s13_240w_avif from "../assets/optimized/r/s13-240.avif";
import s13_480w from "../assets/optimized/r/s13-480.webp";
import s13_480w_avif from "../assets/optimized/r/s13-480.avif";
import s13_960w from "../assets/optimized/r/s13-960.webp";
import s13_960w_avif from "../assets/optimized/r/s13-960.avif";
import s13_fb from "../assets/optimized/r/s13-960.webp";
import s14_orig from "../assets/s14.png";
import s14_240w from "../assets/optimized/r/s14-240.webp";
import s14_240w_avif from "../assets/optimized/r/s14-240.avif";
import s14_480w from "../assets/optimized/r/s14-480.webp";
import s14_480w_avif from "../assets/optimized/r/s14-480.avif";
import s14_960w from "../assets/optimized/r/s14-960.webp";
import s14_960w_avif from "../assets/optimized/r/s14-960.avif";
import s14_fb from "../assets/optimized/r/s14-960.webp";
import s42_orig from "../assets/s42.png";
import s42_240w from "../assets/optimized/r/s42-240.webp";
import s42_240w_avif from "../assets/optimized/r/s42-240.avif";
import s42_480w from "../assets/optimized/r/s42-480.webp";
import s42_480w_avif from "../assets/optimized/r/s42-480.avif";
import s42_960w from "../assets/optimized/r/s42-960.webp";
import s42_960w_avif from "../assets/optimized/r/s42-960.avif";
import s42_fb from "../assets/optimized/r/s42-960.webp";
import f1_orig from "../assets/f1.png";
import f1_240w from "../assets/optimized/r/f1-240.webp";
import f1_240w_avif from "../assets/optimized/r/f1-240.avif";
import f1_480w from "../assets/optimized/r/f1-480.webp";
import f1_480w_avif from "../assets/optimized/r/f1-480.avif";
import f1_960w from "../assets/optimized/r/f1-960.webp";
import f1_960w_avif from "../assets/optimized/r/f1-960.avif";
import f1_fb from "../assets/optimized/r/f1-960.webp";
import f2_orig from "../assets/f2.png";
import f2_240w from "../assets/optimized/r/f2-240.webp";
import f2_240w_avif from "../assets/optimized/r/f2-240.avif";
import f2_480w from "../assets/optimized/r/f2-480.webp";
import f2_480w_avif from "../assets/optimized/r/f2-480.avif";
import f2_960w from "../assets/optimized/r/f2-960.webp";
import f2_960w_avif from "../assets/optimized/r/f2-960.avif";
import f2_fb from "../assets/optimized/r/f2-960.webp";
import f20_orig from "../assets/f20.png";
import f20_240w from "../assets/optimized/r/f20-240.webp";
import f20_240w_avif from "../assets/optimized/r/f20-240.avif";
import f20_480w from "../assets/optimized/r/f20-480.webp";
import f20_480w_avif from "../assets/optimized/r/f20-480.avif";
import f20_960w from "../assets/optimized/r/f20-960.webp";
import f20_960w_avif from "../assets/optimized/r/f20-960.avif";
import f20_fb from "../assets/optimized/r/f20-960.webp";
import f24_orig from "../assets/f24.png";
import f24_240w from "../assets/optimized/r/f24-240.webp";
import f24_240w_avif from "../assets/optimized/r/f24-240.avif";
import f24_480w from "../assets/optimized/r/f24-480.webp";
import f24_480w_avif from "../assets/optimized/r/f24-480.avif";
import f24_960w from "../assets/optimized/r/f24-960.webp";
import f24_960w_avif from "../assets/optimized/r/f24-960.avif";
import f24_fb from "../assets/optimized/r/f24-960.webp";
import gift_orig from "../assets/gift.jpg";
import gift_240w from "../assets/optimized/r/gift-240.webp";
import gift_240w_avif from "../assets/optimized/r/gift-240.avif";
import gift_480w from "../assets/optimized/r/gift-480.webp";
import gift_480w_avif from "../assets/optimized/r/gift-480.avif";
import gift_960w from "../assets/optimized/r/gift-960.webp";
import gift_960w_avif from "../assets/optimized/r/gift-960.avif";
import gift_fb from "../assets/optimized/r/gift-960.webp";
import ff1_orig from "../assets/flower/ff1.jpg";
import ff1_240w from "../assets/optimized/r/ff1-240.webp";
import ff1_240w_avif from "../assets/optimized/r/ff1-240.avif";
import ff1_480w from "../assets/optimized/r/ff1-480.webp";
import ff1_480w_avif from "../assets/optimized/r/ff1-480.avif";
import ff1_960w from "../assets/optimized/r/ff1-960.webp";
import ff1_960w_avif from "../assets/optimized/r/ff1-960.avif";
import ff1_fb from "../assets/optimized/r/ff1-960.webp";

// Maps an original asset's module URL to a responsive set of pre-built srcset
// strings. All derived assets are referenced by direct named imports so they
// are never tree-shaken from the production bundle.
export const RESP_BY_ORIGINAL = {};
  RESP_BY_ORIGINAL[dev1_orig] = {
    avif: `${dev1_240w_avif} 240w, ${dev1_480w_avif} 480w, ${dev1_960w_avif} 960w`,
    webp: `${dev1_240w} 240w, ${dev1_480w} 480w, ${dev1_960w} 960w`,
    fallback: dev1_fb,
    original: dev1_orig,
    w: 736,
  };
  RESP_BY_ORIGINAL[dev3_orig] = {
    avif: `${dev3_240w_avif} 240w, ${dev3_480w_avif} 480w, ${dev3_960w_avif} 960w`,
    webp: `${dev3_240w} 240w, ${dev3_480w} 480w, ${dev3_960w} 960w`,
    fallback: dev3_fb,
    original: dev3_orig,
    w: 1200,
  };
  RESP_BY_ORIGINAL[bride1_orig] = {
    avif: `${bride1_240w_avif} 240w, ${bride1_480w_avif} 480w, ${bride1_960w_avif} 960w`,
    webp: `${bride1_240w} 240w, ${bride1_480w} 480w, ${bride1_960w} 960w`,
    fallback: bride1_fb,
    original: bride1_orig,
    w: 736,
  };
  RESP_BY_ORIGINAL[bride7_orig] = {
    avif: `${bride7_240w_avif} 240w, ${bride7_480w_avif} 480w, ${bride7_960w_avif} 960w`,
    webp: `${bride7_240w} 240w, ${bride7_480w} 480w, ${bride7_960w} 960w`,
    fallback: bride7_fb,
    original: bride7_orig,
    w: 736,
  };
  RESP_BY_ORIGINAL[r1_orig] = {
    avif: `${r1_240w_avif} 240w, ${r1_480w_avif} 480w, ${r1_960w_avif} 960w`,
    webp: `${r1_240w} 240w, ${r1_480w} 480w, ${r1_960w} 960w`,
    fallback: r1_fb,
    original: r1_orig,
    w: 736,
  };
  RESP_BY_ORIGINAL[r9_orig] = {
    avif: `${r9_240w_avif} 240w, ${r9_480w_avif} 480w, ${r9_960w_avif} 960w`,
    webp: `${r9_240w} 240w, ${r9_480w} 480w, ${r9_960w} 960w`,
    fallback: r9_fb,
    original: r9_orig,
    w: 736,
  };
  RESP_BY_ORIGINAL[r10_orig] = {
    avif: `${r10_240w_avif} 240w, ${r10_480w_avif} 480w, ${r10_960w_avif} 960w`,
    webp: `${r10_240w} 240w, ${r10_480w} 480w, ${r10_960w} 960w`,
    fallback: r10_fb,
    original: r10_orig,
    w: 736,
  };
  RESP_BY_ORIGINAL[r12_orig] = {
    avif: `${r12_240w_avif} 240w, ${r12_480w_avif} 480w, ${r12_960w_avif} 960w`,
    webp: `${r12_240w} 240w, ${r12_480w} 480w, ${r12_960w} 960w`,
    fallback: r12_fb,
    original: r12_orig,
    w: 736,
  };
  RESP_BY_ORIGINAL[anni10_orig] = {
    avif: `${anni10_240w_avif} 240w, ${anni10_480w_avif} 480w, ${anni10_960w_avif} 960w`,
    webp: `${anni10_240w} 240w, ${anni10_480w} 480w, ${anni10_960w} 960w`,
    fallback: anni10_fb,
    original: anni10_orig,
    w: 736,
  };
  RESP_BY_ORIGINAL[baby_orig] = {
    avif: `${baby_240w_avif} 240w, ${baby_480w_avif} 480w, ${baby_960w_avif} 960w`,
    webp: `${baby_240w} 240w, ${baby_480w} 480w, ${baby_960w} 960w`,
    fallback: baby_fb,
    original: baby_orig,
    w: 736,
  };
  RESP_BY_ORIGINAL[birthday1_orig] = {
    avif: `${birthday1_240w_avif} 240w, ${birthday1_480w_avif} 480w, ${birthday1_960w_avif} 960w`,
    webp: `${birthday1_240w} 240w, ${birthday1_480w} 480w, ${birthday1_960w} 960w`,
    fallback: birthday1_fb,
    original: birthday1_orig,
    w: 832,
  };
  RESP_BY_ORIGINAL[birthday10_orig] = {
    avif: `${birthday10_240w_avif} 240w, ${birthday10_480w_avif} 480w, ${birthday10_960w_avif} 960w`,
    webp: `${birthday10_240w} 240w, ${birthday10_480w} 480w, ${birthday10_960w} 960w`,
    fallback: birthday10_fb,
    original: birthday10_orig,
    w: 736,
  };
  RESP_BY_ORIGINAL[s10_orig] = {
    avif: `${s10_240w_avif} 240w, ${s10_480w_avif} 480w, ${s10_960w_avif} 960w`,
    webp: `${s10_240w} 240w, ${s10_480w} 480w, ${s10_960w} 960w`,
    fallback: s10_fb,
    original: s10_orig,
    w: 900,
  };
  RESP_BY_ORIGINAL[s12_orig] = {
    avif: `${s12_240w_avif} 240w, ${s12_480w_avif} 480w, ${s12_960w_avif} 960w`,
    webp: `${s12_240w} 240w, ${s12_480w} 480w, ${s12_960w} 960w`,
    fallback: s12_fb,
    original: s12_orig,
    w: 1200,
  };
  RESP_BY_ORIGINAL[s13_orig] = {
    avif: `${s13_240w_avif} 240w, ${s13_480w_avif} 480w, ${s13_960w_avif} 960w`,
    webp: `${s13_240w} 240w, ${s13_480w} 480w, ${s13_960w} 960w`,
    fallback: s13_fb,
    original: s13_orig,
    w: 720,
  };
  RESP_BY_ORIGINAL[s14_orig] = {
    avif: `${s14_240w_avif} 240w, ${s14_480w_avif} 480w, ${s14_960w_avif} 960w`,
    webp: `${s14_240w} 240w, ${s14_480w} 480w, ${s14_960w} 960w`,
    fallback: s14_fb,
    original: s14_orig,
    w: 720,
  };
  RESP_BY_ORIGINAL[s42_orig] = {
    avif: `${s42_240w_avif} 240w, ${s42_480w_avif} 480w, ${s42_960w_avif} 960w`,
    webp: `${s42_240w} 240w, ${s42_480w} 480w, ${s42_960w} 960w`,
    fallback: s42_fb,
    original: s42_orig,
    w: 1080,
  };
  RESP_BY_ORIGINAL[f1_orig] = {
    avif: `${f1_240w_avif} 240w, ${f1_480w_avif} 480w, ${f1_960w_avif} 960w`,
    webp: `${f1_240w} 240w, ${f1_480w} 480w, ${f1_960w} 960w`,
    fallback: f1_fb,
    original: f1_orig,
    w: 656,
  };
  RESP_BY_ORIGINAL[f2_orig] = {
    avif: `${f2_240w_avif} 240w, ${f2_480w_avif} 480w, ${f2_960w_avif} 960w`,
    webp: `${f2_240w} 240w, ${f2_480w} 480w, ${f2_960w} 960w`,
    fallback: f2_fb,
    original: f2_orig,
    w: 656,
  };
  RESP_BY_ORIGINAL[f20_orig] = {
    avif: `${f20_240w_avif} 240w, ${f20_480w_avif} 480w, ${f20_960w_avif} 960w`,
    webp: `${f20_240w} 240w, ${f20_480w} 480w, ${f20_960w} 960w`,
    fallback: f20_fb,
    original: f20_orig,
    w: 656,
  };
  RESP_BY_ORIGINAL[f24_orig] = {
    avif: `${f24_240w_avif} 240w, ${f24_480w_avif} 480w, ${f24_960w_avif} 960w`,
    webp: `${f24_240w} 240w, ${f24_480w} 480w, ${f24_960w} 960w`,
    fallback: f24_fb,
    original: f24_orig,
    w: 656,
  };
  RESP_BY_ORIGINAL[gift_orig] = {
    avif: `${gift_240w_avif} 240w, ${gift_480w_avif} 480w, ${gift_960w_avif} 960w`,
    webp: `${gift_240w} 240w, ${gift_480w} 480w, ${gift_960w} 960w`,
    fallback: gift_fb,
    original: gift_orig,
    w: 736,
  };
  RESP_BY_ORIGINAL[ff1_orig] = {
    avif: `${ff1_240w_avif} 240w, ${ff1_480w_avif} 480w, ${ff1_960w_avif} 960w`,
    webp: `${ff1_240w} 240w, ${ff1_480w} 480w, ${ff1_960w} 960w`,
    fallback: ff1_fb,
    original: ff1_orig,
    w: 736,
  };
